/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flutter_application_uno;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'flutter_application_uno.greeting' plugin.
 */
class Flutter_application_unoPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("flutter_application_uno.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
